[package]
name = "coppice-librustzcash"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
coppice.workspace = true
orchard.workspace = true
zcash_client_backend = { workspace = true, features = ["orchard"] }
zcash_keys = { workspace = true, features = ["orchard", "sapling", "std"] }
zcash_protocol.workspace = true

[dev-dependencies]
incrementalmerkletree.workspace = true
zip32.workspace = true
